#pragma once

#include <istream>
#include <string>

#include "BatchEvaluator.hpp"
#include "EvaluationOptions.hpp"
#include "EvaluationResult.hpp"
#include "scorer.hpp"
#include "tcframe/runner/os.hpp"
#include "tcframe/runner/verdict.hpp"

using std::istream;
using std::string;

namespace tcframe {

// Output-Only: test case outputs are generated by the reference solution (as in Batch), but
// contestants submit only the output. Grading runs no solution; the submitted output is
// compared with the expected one by the scorer.
//
// options.solutionCommand() is the directory holding the submitted outputs, one file per test
// case named like the expected output (e.g. "submissions/foo_1.out" for "tc/foo_1.out").
class OutputOnlyEvaluator : public BatchEvaluator {
public:
    virtual ~OutputOnlyEvaluator() = default;

    using BatchEvaluator::BatchEvaluator;

    EvaluationResult evaluate(
            const string& inputFilename,
            const string& outputFilename,
            const EvaluationOptions& options) {

        string submittedFilename = options.solutionCommand() + "/" + baseName(outputFilename);

        istream* submitted = os_->openForReading(submittedFilename);
        bool exists = submitted->good();
        os_->closeOpenedStream(submitted);
        if (!exists) {
            ExecutionResult executionResult = ExecutionResultBuilder()
                    .setStandardError("Submitted output not found: " + submittedFilename + "\n")
                    .build();
            return {TestCaseVerdict(Verdict::wa()), {{"scorer", executionResult}}};
        }

        ScoringResult scoringResult = scorer_->score(inputFilename, outputFilename, submittedFilename);
        return {scoringResult.verdict(), {{"scorer", scoringResult.executionResult()}}};
    }

private:
    static string baseName(const string& path) {
        size_t slash = path.find_last_of('/');
        return slash == string::npos ? path : path.substr(slash + 1);
    }
};

}
